name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNzhiNWUwZTctZDhlZi00ZmUxLWI2MjMtNTA5YzI5ODk5MWUzIiwidGVuYW50X2lkIjoiNTBhNGFhYTQ1OWJiZTA3MGU5NmQyNGZhODAxN2Y4Yjg3YTA2NTk4ODIwYWM4MWE1MjA4ODQ1ZjI4YWY4MWY2NSIsImludGVybmFsX3NlY3JldCI6ImUwNjc0MjVjLTA2ZDYtNDg4NS04YjhhLTM2OTU5ZjUyOTAzNSJ9.54ERJ_9T2aH0pxhSr9KlEZdXRqTWbgAkHShCAVFpYnk"
JWT_SECRET = "I AM BATmAN"